In [ ]:
print("BEM VINDO A CALCULADORA DE IMC!!!")
peso= int(input("Digite o seu peso: "))
altura= float(input("Digite sua altura: "))
IMC= peso/(altura*altura) 
print("Seu IMC é: ", IMC)

In [ ]:
cidade= input("Digite o nome da sua cidade: ")
ano= int(input("Digite o ano recorrente: "))
temperatura= int(input("Digite a temperatura média da sua cidade: "))
print("O nome da sua cidade é ", cidade, ", o ano recorrente é ", ano, ", e a temperatura média da sua cidade é ", temperatura)

In [ ]:
opcao= 1
while opcao != 0:
  print("BEM VINDO A CALCULADORA!!!")
  num1= float(input("Digite o primeiro número: "))
  num2= float(input("Digite o segundo número: "))
  print("OPERAÇÕES DISPONÍVEIS:")
  print("1- Soma")
  print("2- Subtração")
  print("3- Multiplicação")
  print("4- Divisão")
  operacao= int(input("Digite o n° da operação desejada: "))
  if operacao == 1:
    resultado= num1 + num2
  elif operacao == 2:
    resultado= num1 - num2
  elif operacao == 3:
    resultado= num1 * num2
  elif operacao == 4:
    resultado= num1 / num2
  else:
    print("Número inválido, Digite novamente.")
  print("Resultado: ", resultado)
  opcao= int(input("Digite 0 para sair da calculadora ou 1 para fazer uma nova operação: "))
print("Fechando calculadora...")
print("Programa fechado!")

In [ ]:
opcao= 1
while opcao != 0:
  print("BEM VINDO A CALCULADORA MAIOR E MENOR!!!")
  num1= float(input("Digite o primeiro número: "))
  num2= float(input("Digite o segundo número: "))
  if num1 > num2:
    print("O número 1 é maior que o número 2.")
  elif num1 < num2:
    print("O número 2 é maior que o número 1.")
  else:
    print("Os números são iguais.")
  opcao= int(input("Digite 0 para sair da calculadora ou 1 para fazer uma nova operação: "))
print("Fechando calculadora...")
print("Programa fechado!")

In [ ]:
print("BEM VINDO AO DETECTOR DE PAR OU IMPAR!!!")
num= int(input("Digite um número: "))
if num % 2 == 0:
    print("O número é par.")
else:
    print("O número é impar.")

In [ ]:
print("BEM VINDO AO CARTÓRIO DO PINTA")
print("OPÇÕES DISPONÍVEIS")
print("C ()Casado")
print("S ()Solteiro")
print("D ()Divorciado")
print("V ()Viúvo")
print("O ()Outros")
civil = input("Digite seu estado civil: ").upper()
if civil == "C":
    print("C - Casado")
elif civil == "S":
    print("S - Solteiro")
elif civil == "D":
    print("D - Divorciado")
elif civil == "V":
    print("V - Viúvo")
else:
    print("O - Outros")

In [ ]:
idade = int(input("Digite a sua idade: "))
if idade > 16 and idade < 18:
    print("Seu voto é facultativo.")
elif idade >= 70:
    print("Seu voto é facultativo.")
elif idade <= 16:
    print("Não pode votar.")
else:
    print("Seu voto é obrigatório.")

In [ ]:
idade = int(input("Digite a sua idade nadador: "))
if idade >= 5 and idade <= 7:
    print("Infantil A")
elif idade >= 8 and idade <= 11:
    print("Infantil B")
elif idade >= 12 and idade <= 13:
    print("Juvenil A")
elif idade >= 14 and idade <= 17:
    print("Juvenil B")
else:
    print("Adultos")

In [ ]:
opcao= 1
while opcao != 0:
  print("BEM VINDO A CALCULADORA!!!")
  num1= float(input("Digite o primeiro número: "))
  num2= float(input("Digite o segundo número: "))
  print("OPERAÇÕES DISPONÍVEIS:")
  print("1- Soma")
  print("2- Subtração")
  print("3- Multiplicação")
  print("4- Divisão")
  operacao= int(input("Digite o n° da operação desejada: "))
  if operacao == 1:
    resultado= num1 + num2
  elif operacao == 2:
    resultado= num1 - num2
  elif operacao == 3:
    resultado= num1 * num2
  elif operacao == 4:
    resultado= num1 / num2
  else:
    print("Número inválido, Digite novamente.")
  print(f"Resultado: {resultado:.2f}")
  opcao= int(input("Digite 0 para sair da calculadora ou 1 para fazer uma nova operação: "))
print("Fechando calculadora...")
print("Programa fechado!")

In [ ]:
numero=0
soma= int(1)
while soma != 0:
    soma= int(input("Digite um número, para encerrar digite 0:"))
    numero += soma
print(f"A soma de todos os números que você digitou é: {numero}")

In [ ]:
cont = 0
resultado = 0
op = 1
while op != 0:
    nota= float(input("Digite a sua nota para obter a média: "))
    resultado += nota
    cont += 1
    op= int(input("Digite 1 para adicionar mais uma nota, ou 0 para encerrar a operação: "))
resultado_final = resultado / cont
print("A média aritmética das suas notas é: ", resultado_final)

In [ ]:
x = int(input("Digite o número que você quer visualizar a tabuada: "))
for i in range(1,11,1):
    print(f"{x} x {i} = {x*i}")

In [ ]:
for i in range (10, 0, -1):
    print(f"6 x {i} = {6 * x}")

In [ ]:
x = int(input("Digite o número que você quer visualizar a tabuada: "))
for i in range(10,0,-1):
    print(f"{x} x {i} = {x*i}")

In [ ]:
x = int(input("Digite o número que você quer visualizar o fatorial: "))
fat = 1
for i in range(1, x + 1, 1):
    fat *= i
print(f"O fatorial do número {x} é: {fat}")

In [ ]:
primeiro_termo = int(input("Digite o primeiro termo da PA: "))
razao = int(input("Digite a razão da PA: "))
final = int(input("Digite o último termo da PA: "))

print("-" * 20)
print("Progressão Aritmética:")

for i in range(primeiro_termo, final+1, razao):
    print(i, end=" -> ")

print("FIM")
print("-" * 20)

In [ ]:
termo1 = float(input("Digite o primeiro termo da PG: "))
razao = float(input("Digite a razão da PG: "))
final = int(input("Digite quantos termos você quer mostrar: "))

print(f"\nProgressão Geométrica ({final} termos):")

for i in range(final):
    termo_atual = termo1 * (razao ** i)
    print(f"Termo {i+1}: {termo_atual}")

In [ ]:
inicio= int(input("Digite o primeiro termo: "))
final= int(input("Digite o número final: "))
razao= int(input("Digite a razão da PG: "))
print("Progressão Geométrica:")

termo=inicio
for i in range(inicio,final+1):
    if termo<=final:
        print(termo,end=",")
        termo*=razao
    else:
        break

In [ ]:
inicio = int(input("Digite o primeiro termo: "))
final = int(input("Digite o número final: "))
razao = int(input("Digite a razão da PG: "))
print("Progressão Geométrica:")

termo = inicio
for i in range(inicio, final + 1):
    if termo <= final:
        proximo = termo * razao
        
        if proximo > final:
            print(termo, end=".")
        else:
            print(termo, end=",")
            
        termo = proximo
    else:
        break

In [ ]:
n = int(input("Digite o número de elementos que você quer visualizar a SF: "))
a, b = 0, 1

print("-" * 30)
print("Sequência de Fibonacci:")

for _ in range(n):
    print(a, end=" -> ")
    a, b = b, a + b

print("FIM")
print("-" * 30)

In [ ]:
n = int(input("Digite o número de elementos que você quer visualizar a SF: "))
anterior = 0
atual = 1
print("Sequência Fibonacci: ")
for i in range(n):
    print(atual,end=" ")
    proximo=anterior+atual
    anterior=atual
    atual=proximo

In [ ]:
letra = ["a", "b", "c", "d", "e", "f"]
print(f"Tamanho da lista: {len(letra)}")
print(f"Índice da letra b: {letra.index("b")}")
var = input("Informe o valor procurado: ")
if var.lower() in letra:
    print(f"A letra {var.lower()}, está na lista.")
else:
    print (f"A letra {var.lower()}, não está na lista")

In [ ]:
nova=[]
num=int(input("Digite um número para a lista (0 para sair): "))
while num != 0:
    nova.append(num)
    num=int(input("Digite um número para a lista (0 para sair): "))
print(nova)

In [ ]:
lista = [5, 4, 3, 2, 1]
print(lista)

In [ ]:
lista = [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 10.0]
lista.reverse()
print(lista)

In [ ]:
notas = []
cont = 1
while cont != 5:
    inserir = float(input(f"Digite a nota {cont}: "))
    notas.append (inserir)
    cont+=1
print(notas)
soma=0
for i in notas:
    soma += i #OU sum(notas) para somar todos os termos da lista
media = soma / (cont-1) #OU media = soma / len(notas)
print(f"A média das notas é: {media:.2f}")

In [2]:
tupla = 1,2,3,4
print(tupla[1])
#unica diferença de tupla para lista é que a lista é mútavel e a tupla não, ou seja, não da para alterar/mexer

2

In [3]:
dic = {"Curso":"Python", "Professor":"Ricardo"}
print(f"O curso de {dic["Curso"]}, é ministrado pelo professor {dic["Professor"]}")

O curso de Python, é ministrado pelo professor Ricardo

In [4]:
produtos = {
    "Mouse":98.75,
    "Teclado":125.65,
    "Monitor":134.78,
    "Gabinete":170.00,
    "HD Externo":510.50,
    "Headset":125.45}
while True:
  produto= input("Informe o produto a pesquisar o preço ou fim para sair: ")
  if produto == "fim":
    break
  if produto in produtos:
    print(f"Produto {produto} custa {produtos[produto]}$.")
  else:
    print(f"Produto {produto} não encontrado.")

Produto Mouse custa 98.75$.

In [5]:
dic = {"Nome":"Fulano", "Sobrenome":"De tal"}
local = {"UF":"SP", "Cidade":"São Carlos"}
dic2 = dic.copy()
dic.update(local)
print(len(dic))
print(f"dic: {dic}")
print(f"dic2: {dic2}")

4
dic: {'Nome': 'Fulano', 'Sobrenome': 'De tal', 'UF': 'SP', 'Cidade': 'São Carlos'}
dic2: {'Nome': 'Fulano', 'Sobrenome': 'De tal'}

In [6]:
livro1 = {
  "Título":"O grande campeão",
  "Autor":"Pinta",
  "Ano":2026  
}

livro2 = {
  "Título":"O mar serenou",
  "Autor":"Maria Helena",
  "Ano":2024  
}

livro3 = {
  "Título":"A praia",
  "Autor":"Deus",
  "Ano":2000  
}

for chave, valor in livro1.items():
  print(f"{chave}: {valor}", end=" | ")

for chave, valor in livro2.items():
  print(f"{chave}: {valor}", end=" | ")  
  
for chave, valor in livro3.items():
  print(f"{chave}: {valor}", end=" | ")

Título: O grande campeão | Autor: Pinta | Ano: 2026 | Título: O mar serenou | Autor: Maria Helena | Ano: 2024 | Título: A praia | Autor: Deus | Ano: 2000 |

In [7]:
livros = [
  {
    "Título":"O grande campeão",
    "Autor":"Pinta",
    "Ano":2026   
  },  

  {
    "Título":"O mar serenou",
    "Autor":"Maria Helena",
    "Ano":2024   
  },

  {
    "Título":"A praia",
    "Autor":"Deus",
    "Ano":2000   
  }             
]

print("Informações dos livros: ")
cont=1
for livro in livros:
  print(f"Título{cont}: {livro["Título"]}, Autor{cont}: {livro["Autor"]}, Ano{cont}: {livro["Ano"]}")
  cont+=1

Informações dos livros:
Título1: O grande campeão, Autor1: Pinta, Ano1: 2026
Título2: O mar serenou, Autor2: Maria Helena, Ano2: 2024
Título3: A praia, Autor3: Deus, Ano3: 2000

In [9]:
dic = {
    "Nome":"Alice",
    "Idade":20,
    "Curso":"Engenharia de Software"
}

dic["nota"] = 9.5
print(dic)

{'Nome': 'Alice', 'Idade': 20, 'Curso': 'Engenharia de Software', 'nota': 9.5}

In [12]:
produtos= {
    "Fogão":1200.00,
    "Frigideira":500.00,
    "Panela de pressão":1000.00
}

produtos.pop("Fogão")
#comando para remover chave e valor de um dicionário (.pop()).
for chave, valor in produtos.items():
    print(f"Valor do produto {chave}: {valor}")

Valor do produto Frigideira: 500.0
Valor do produto Panela de pressão: 1000.0

In [ ]:
livros = [
  {
    "Título":"Diário de um Banana",
    "Autor":"Pinta",
    "Ano":2014   
  },  

  {
    "Título":"Clareou",
    "Autor":"Pixote",
    "Ano":2025   
  },

  {
    "Título":"O mar",
    "Autor":"Jesus",
    "Ano":1900   
  }             
]

print("Informações dos livros: ")

cont=1

for livro in livros:
  print(f"Título{cont}: {livro["Título"]}, Autor{cont}: {livro["Autor"]}, Ano{cont}: {livro["Ano"]}")
  cont+=1

livros.pop(0)

print("Livros Atualizados!!!")

cont=1
for livro in livros:
  print(f"Título{cont}: {livro["Título"]}, Autor{cont}: {livro["Autor"]}, Ano{cont}: {livro["Ano"]}")
  cont+=1

#E o comando para remover apenas um item de um dicionario dentro dessa lista como por exemplo o título apenas, o comando fica assim: livros[0].pop("Título").

Informações dos livros:
Título1: Diário de um Banana, Autor1: Pinta, Ano1: 2014
Título2: Clareou, Autor2: Pixote, Ano2: 2025
Título3: O mar, Autor3: Jesus, Ano3: 1900
Livros Atualizados!!!
Título1: Clareou, Autor1: Pixote, Ano1: 2025
Título2: O mar, Autor2: Jesus, Ano2: 1900

In [1]:
livros = []

# Definindo quantos livros o usuário quer adicionar
quantidade = int(input("Quantos livros deseja cadastrar? "))

for i in range(quantidade):
    print(f"\nCadastro do livro {i+1}:")
    titulo = input("Título: ")
    autor = input("Autor: ")
    ano = input("Ano: ")
    
    # Criando o dicionário e adicionando à lista
    novo_livro = {
        "Título": titulo,
        "Autor": autor,
        "Ano": ano
    }
    livros.append(novo_livro)

print("\nInformações dos livros: ")

cont=1
for livro in livros:
    print(f"Título{cont}: {livro['Título']}, Autor: {livro['Autor']}, Ano: {livro['Ano']}")
    cont+=1

livros.pop(0)

print("\nLivros Atualizados!!!")

cont=1
for livro in livros:
    print(f"Título{cont}: {livro['Título']}, Autor: {livro['Autor']}, Ano: {livro['Ano']}")
    cont+=1

Cadastro do livro 1:

Cadastro do livro 2:

Informações dos livros:
Título1: oi, Autor: eu, Ano: 9090
Título2: tchau, Autor: eu, Ano: 0909

Livros Atualizados!!!
Título1: tchau, Autor: eu, Ano: 0909

In [ ]:
import numpy as np

#criar um vetor com o numpy
meu_vetor = np.array([10, 11, 13, 11, 14, 15])
#array é um vetor unidimensional, horizontal ou vertical

#criar matriz 2x3
minha_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(minha_matrix.shape) #resultado: (2, 3)

#cria tensor == conjunto de matrizes
meu_tensor = np.array([[[1, 2, 3], [4, 5, 6,]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(meu_tensor.shape) #resultado: (3, 2, 3)

In [6]:
vetor= np.array([1, 2, 3])

vetor= np.append(vetor, [4, 5, 6])
print(vetor)

vetor= np.delete(vetor, 0)
print(vetor)

[1 2 3 4 5 6]
[2 3 4 5 6]

In [ ]:
import numpy as np

a= np.array([9, 6, 12, 16, 20])
b= np.copy(a)
print(a)
print(b)
b[0]=19
print(a)
print(b)
result=np.concatenate((a,b))
print(result)
x, y=np.split(result, 2)
print(x)
print(y)

[ 9  6 12 16 20]
[ 9  6 12 16 20]
[ 9  6 12 16 20]
[19  6 12 16 20]
[ 9  6 12 16 20 19  6 12 16 20]
[ 9  6 12 16 20]
[19  6 12 16 20]

In [11]:
matriz= np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(matriz[1, : ])
b= np.copy(matriz)
print(b[0,1:4])

[5 6 7 8]
[2 3 4]

In [ ]:
import numpy as np


a= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]) #ou usar .arange(x) para preencher a quantidade de números mais rápido
b= a.reshape(3, 4)
print(b)
print (b[1])
print(b[2][3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
11

In [20]:
a= np.array([1, 2, 3])
b= np.array([4, 5, 6])
c= np.concatenate((a, b))
print(c[1:5])

[2 3 4 5]

In [24]:
a= np.array([10, 20, 30, 40, 50])
b= np.copy(a)
b= np.delete(b, [1, 2])
print(a)
print(b)

[10 20 30 40 50]
[10 40 50]

In [23]:
a= np.array([100, 200, 300, 400, 500, 600])
x, y= np.split(a, 2)
print("Vetores Iniciais:")
print(x)
print(y)

print("Vetores Atualizados: ")
y= np.append(y, 700)
print(x)
print(y)

Vetores Iniciais:
[100 200 300]
[400 500 600]
Vetores Atualizados:
[100 200 300]
[400 500 600 700]

In [28]:
a= np.array([8, 4, 9, 2])
b= np.array([2, 4, 3, 2.5])
print(a, b)

c= np.add(a, b) #adição dos vetores 
print(c)

c= np.subtract(a, b) #subtração
print(c)

c= np.multiply(a, b) #multiplicação
print(c)

c= np.divide(a, b) #divisão
print(c)

c= np.power(a, b) #potência
print(c)

c= np.sqrt(a) #raiz quadrada
print(c)

[8 4 9 2] [2.  4.  3.  2.5]
[10.   8.  12.   4.5]
[ 6.   0.   6.  -0.5]
[16. 16. 27.  5.]
[4.  1.  3.  0.8]
[ 64.         256.         729.           5.65685425]
[2.82842712 2.         3.         1.41421356]

In [5]:
import numpy as np

a= np.array([[1], [2], [3]])
b= np.array([10, 20, 30])
c= a+b
print(a)
print(b)
print(c)

[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]

In [9]:
a= np.array([10, 20, 30 , 40, 50])
b= np.array([1, 2, 3, 4, 5])
print(a)
print(b)

c= np.add(a, b)
print(c)
c= np.subtract( a, b)
print(c)
c= np.multiply(a, b)
print(c)
c= np.divide(a, b)
print(c)

[10 20 30 40 50]
[1 2 3 4 5]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]

In [ ]:
a= np.array([12, 15, 20, 25, 30, 35, 40])
print(a)

c= np.sum(a)
print(c) #OU print(np.sum(a, b)) para não precisar guardar o valor em outra variável
c= np.mean(a)
print(c)
c= np.std(a)
print(c)
c= np.max(a)
print(c)
c= np.min(a)
print(c)

[12 15 20 25 30 35 40]
177
25.285714285714285
9.587406706035724
40
12

In [8]:
import numpy as np

a= np.array([[1, 2, 3], [4, 5, 6]])
b= np.array([10, 20, 30])
print(a)
print(b)

c= a+b
print(c)

d= np.multiply(c, 2)
print(d)

[[1 2 3]
 [4 5 6]]
[10 20 30]
[[11 22 33]
 [14 25 36]]
[[22 44 66]
 [28 50 72]]

In [6]:
a= np.array([[10], [20], [30]])
b= np.array([1, 2, 3])

c= np.multiply(a, b)

print(a)
print(b)
print(c)

[[10]
 [20]
 [30]]
[1 2 3]
[[10 20 30]
 [20 40 60]
 [30 60 90]]

In [14]:
import pandas as pd

df= pd.DataFrame(
    {
        "Nome": [
            "Arthur Ongaro de Lima",
            "Bianca Ongaro de Lima",
            "Wanderson Luis Gomes de Lima",
            "Priscila Júlio Ongaro de Lima"
        ],

            "Idade": [19, 25, 50, 46],
            "Sexo": [
                "Masculino",
                "Feminino",
                "Masculino",
                "Feminino"
            ]
    }
)
df
#df["Idade"] para pegar apenas a coluna das idades

                            Nome  Idade       Sexo
0          Arthur Ongaro de Lima     19  Masculino
1          Bianca Ongaro de Lima     25   Feminino
2   Wanderson Luis Gomes de Lima     50  Masculino
3  Priscila Júlio Ongaro de Lima     46   Feminino

In [ ]:
df= pd.read_csv("vinhos.csv")
df= pd.read_json("vinhos.json")
df= pd.read_excel("tips.xlsx")
#Três tipos de comandos para ler documentos em texto (csv), excel (xlsx) e json.
#E exibir em forma de DataFrame do pandas (Planilha do python)

In [ ]:
import os
print(os.getcwd())
#comando para saber aonde este arquivo está

c:\Users\Aluno\Desktop\pasta Arthur Lima REAL\SENAI-PPDC

In [ ]:
import pandas as pd

df= pd.read_csv("vinhos.csv")
df.head(3) #comando para pegar os primeiros 3 itens do arquivo
df.tail(3) #comando para pegar os últimos 3 itens do arquivo

,year,month,location,location_type,category,grape_type,volume_hl,value_usd
26637,2024,12,China,Country,Export,Table,2115,6153.84
26638,2024,12,China,Country,Export,Wine,2107,9355.02
26639,2024,12,China,Country,Export,Sparkling,6813,23101.92

In [ ]:
import pandas as pd

df= pd.read_csv("vinhos.csv")

df.describe() #para fazer uma análise geral
df.describe(percentiles=[0.3, 0.5, 0.7]) #para dividir a tabela do jeito que você quiser, por porcentagem.
df.info(show_counts=True, memory_usage=True, verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 26640 entries, 0 to 26639
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           26640 non-null  int64
 1   month          26640 non-null  int64
 2   location       26640 non-null  str
 3   location_type  26640 non-null  str
 4   category       26640 non-null  str
 5   grape_type     26640 non-null  str
 6   volume_hl      26640 non-null  int64
 7   value_usd      26640 non-null  float64
dtypes: float64(1), int64(3), str(4)
memory usage: 1.6 MB

In [ ]:
df= pd.read_csv("vinhos.csv")

df.shape #mostra a quantidade de linhas
df.columns #mostra os títulos de cada coluna
list(df.columns) #lista todos os títulos das colunas

['year',
 'month',
 'location',
 'location_type',
 'category',
 'grape_type',
 'volume_hl',
 'value_usd']

In [24]:
df= pd.read_csv("vinhos.csv")

df2= df.copy()

#comando para alterar os registros das linhas e coluna especificadas para nulo/none
df2.loc[2:5, "value_usd"]=None 
df2.loc[1:6, "month"]=None

df2.head(7)

#comando para mostrar a quantidade de registros vazios somados, tirar o sum para mostrar pela tabela
df2.isnull().sum() 

#este mostra apenas a quantidade, sem a tabela mostrando a quantidade de cada coluna.
df2.isnull().sum().sum()

np.int64(10)

In [25]:
df= pd.read_csv("vinhos.csv")

df.head()

,year,month,location,location_type,category,grape_type,volume_hl,value_usd
0,2015,1,AC,Brazil_State,Production,Table,910,1782.31
1,2015,1,AC,Brazil_State,Production,Wine,3822,11435.90
2,2015,1,AC,Brazil_State,Production,Sparkling,516,902.97
3,2015,1,AC,Brazil_State,Sales,Table,3494,10491.74
4,2015,1,AC,Brazil_State,Sales,Wine,180,279.26

In [27]:
df= pd.read_csv("vinhos.csv")

df.shape

(26640, 8)

In [29]:
df= pd.read_csv("vinhos.csv")

df.info(show_counts=True, memory_usage=True, verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 26640 entries, 0 to 26639
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           26640 non-null  int64
 1   month          26640 non-null  int64
 2   location       26640 non-null  str
 3   location_type  26640 non-null  str
 4   category       26640 non-null  str
 5   grape_type     26640 non-null  str
 6   volume_hl      26640 non-null  int64
 7   value_usd      26640 non-null  float64
dtypes: float64(1), int64(3), str(4)
memory usage: 1.6 MB

In [28]:
df= pd.read_csv("vinhos.csv")

df.describe()

               year         month     volume_hl    value_usd
count  26640.000000  26640.000000  26640.000000  26640.00000
mean    2019.500000      6.500000   2798.185135   8398.65186
std        2.872335      3.452117   1666.405404   6071.43803
min     2015.000000      1.000000     50.000000     87.07000
25%     2017.000000      3.750000   1393.000000   3721.98000
50%     2019.500000      6.500000   2736.000000   7368.98500
75%     2022.000000      9.250000   4068.000000  11741.85750
max     2024.000000     12.000000   6996.000000  34273.99000

In [33]:
df= pd.read_csv("vinhos.csv")

df2= df.copy()

df2.loc[2:5, "value_usd"]=None 
df2.loc[1:6, "month"]=None
df2.loc[10:19, "location_type"]=None

df2.isnull().sum().sum()
df2.describe()

               year         month     volume_hl     value_usd
count  26640.000000  26634.000000  26640.000000  26636.000000
mean    2019.500000      6.501201   2798.185135   8399.373208
std        2.872335      3.451573   1666.405404   6071.402620
min     2015.000000      1.000000     50.000000     87.070000
25%     2017.000000      4.000000   1393.000000   3722.552500
50%     2019.500000      7.000000   2736.000000   7370.080000
75%     2022.000000     10.000000   4068.000000  11742.230000
max     2024.000000     12.000000   6996.000000  34273.990000

In [34]:
df= pd.read_csv("vinhos.csv")

df.describe()

               year         month     volume_hl    value_usd
count  26640.000000  26640.000000  26640.000000  26640.00000
mean    2019.500000      6.500000   2798.185135   8398.65186
std        2.872335      3.452117   1666.405404   6071.43803
min     2015.000000      1.000000     50.000000     87.07000
25%     2017.000000      3.750000   1393.000000   3721.98000
50%     2019.500000      6.500000   2736.000000   7368.98500
75%     2022.000000      9.250000   4068.000000  11741.85750
max     2024.000000     12.000000   6996.000000  34273.99000

In [ ]:
df= pd.read_csv("vinhos.csv")

df.sort_values(by="volume_hl", ascending=True, inplace=True)
df.reset_index(drop=True, inplace=True) #o drop serve para mostrar ou não os index antigos junto com os novos
df

,year,month,location,location_type,category,grape_type,volume_hl,value_usd
2,2024,12,Italy,Country,Export,Table,50,138.36
4,2019,12,MS,Brazil_State,Production,Table,50,88.75
5,2018,12,MA,Brazil_State,Sales,Table,50,98.54
6,2024,8,AC,Brazil_State,Sales,Sparkling,51,144.62
7,2021,9,AM,Brazil_State,Production,Table,51,97.86
...,...,...,...,...,...,...,...,...
26633,2020,7,Argentina,Country,Import,Table,6993,25230.46
26634,2017,7,Australia,Country,Export,Wine,6993,30121.71
26637,2022,11,South Africa,Country,Export,Sparkling,6995,26250.26
26638,2020,7,Spain,Country,Export,Sparkling,6995,20153.54
26639,2016,8,France,Country,Import,Wine,6996,28580.59

In [56]:
df= pd.read_csv("vinhos.csv")

df[(df["month"]>=5)&(df["year"]==2015)] #pesquisa mais precisa de dados na tabela parecido com banco de dados

,year,month,location,location_type,category,grape_type,volume_hl,value_usd
24,2015,5,AC,Brazil_State,Production,Table,3202,6874.53
25,2015,5,AC,Brazil_State,Production,Wine,3993,13529.90
26,2015,5,AC,Brazil_State,Production,Sparkling,1071,2998.98
27,2015,5,AC,Brazil_State,Sales,Table,3893,7638.60
28,2015,5,AC,Brazil_State,Sales,Wine,4848,17480.49
...,...,...,...,...,...,...,...,...
25987,2015,12,China,Country,Import,Wine,6529,18522.63
25988,2015,12,China,Country,Import,Sparkling,698,1578.49
25989,2015,12,China,Country,Export,Table,4996,10938.62
25990,2015,12,China,Country,Export,Wine,2240,10814.86
25991,2015,12,China,Country,Export,Sparkling,1835,7156.33

In [ ]:
df= pd.read_csv("vinhos.csv")

df.loc[0:3] #mostra os itens da linha 0 ate a linha 3
df.loc[0, "category"] #pega o primeiro item da coluna "category"
df.loc[df["month"]>8] #mostra os dados da coluna "month" que são amiores que 8

df.iloc[0,3] # serve para mostrar os valores por linha e coluna, sem precisar colocar o nome
df.iloc[0:3, 1:4] #mostra a quantidade de linhas e colunas que você especificar

   month location location_type
0      1       AC  Brazil_State
1      1       AC  Brazil_State
2      1       AC  Brazil_State

In [ ]:
df= pd.read_csv("vinhos.csv")


df= df.dropna() #este comando tira todos os valores nulos da tabela
df.isnull().sum()
df2= df.copy()
df2.dropna(axis=1) #apaga os valores nulos da coluna "1"
df2.head()

,year,month,location,location_type,category,grape_type,volume_hl,value_usd
0,2015,1,AC,Brazil_State,Production,Table,910,1782.31
1,2015,1,AC,Brazil_State,Production,Wine,3822,11435.90
2,2015,1,AC,Brazil_State,Production,Sparkling,516,902.97
3,2015,1,AC,Brazil_State,Sales,Table,3494,10491.74
4,2015,1,AC,Brazil_State,Sales,Wine,180,279.26

In [23]:
import pandas as pd 

df= pd.read_excel("tips.xlsx")

df2=df.copy()
df2["size"]=df2["size"].fillna(df2["size"].mean()) #este comando preenche a coluna "size" com a média/mean dos numeros dessa coluna aonde tem valores nulos
df2.head(7)

            total_bill                  tip     sex smoker  day    time  size
0                16.99  2026-01-01 00:00:00  Female     No  Sun  Dinner     2
1                10.34                 1.66    Male     No  Sun  Dinner     3
2  2026-01-21 00:00:00  2026-05-03 00:00:00    Male     No  Sun  Dinner     3
3                23.68                 3.31    Male     No  Sun  Dinner     2
4                24.59                 3.61  Female     No  Sun  Dinner     4
5                25.29                 4.71    Male     No  Sun  Dinner     4
6                 8.77                    2    Male     No  Sun  Dinner     2

In [ ]:
df= pd.read_excel("tips.xlsx")

df2= df.copy()
df2= pd.concat([df2, df2]) #este comando serve para duplicar os dataframes, multiplicar entre si.
df2= df2.drop_duplicates() #este serve para remover todos os dados duplicados, que são diferentes de valores que são iguais.
df2.shape

(243, 7)

In [ ]:
df= pd.read_csv("vinhos.csv")

#este comando serve para fazer cálculos entre as colunas, no caso os valores de uma divididos por outra, 
#criando uma nova coluna.
df["value_per_h1"]=df["value_usd"]/df["volume_hl"] 
df.head()

,year,month,location,location_type,category,grape_type,volume_hl,value_usd,value_per_h1
0,2015,1,AC,Brazil_State,Production,Table,910,1782.31,1.958582
1,2015,1,AC,Brazil_State,Production,Wine,3822,11435.90,2.992125
2,2015,1,AC,Brazil_State,Production,Sparkling,516,902.97,1.749942
3,2015,1,AC,Brazil_State,Sales,Table,3494,10491.74,3.002788
4,2015,1,AC,Brazil_State,Sales,Wine,180,279.26,1.551444

In [ ]:
df= pd.read_csv("vinhos.csv")

#este serve para fazer a contagem da quantidade de vezes em que aparece os valores da coluna especificada
df["category"].value_counts(normalize=True) #normalize=True serve para dar o valor em decimal, ou seja, para porcentagem

category
Production    9720
Sales         9720
Import        3600
Export        3600
Name: count, dtype: int64

In [ ]:
df= pd.read_csv("vinhos.csv")

#agora este pega todos os dados dessas colunas, atribui a variável "dfValues"
dfValues=df.loc[:,["category", "value_usd", "volume_hl"]]
dfValues.groupby("category").mean() #Agrupa e mostra a média da repetição dos valores dessas duas colunas

            value_usd  volume_hl
category
Export       34163.24       6995
Import       34273.99       6996
Production   19764.03       4999
Sales        19612.58       4999

In [ ]:
df= pd.read_csv("vinhos.csv")

mediaPopulacao= df["value_usd"].mean()
#frac=0.1 serve para pegar apenas 10 porcento de todo o dataframe
amostra= df.sample(frac=0.1, random_state=42) #random serve para pegar valores aleatórios, e o state 42 serve para fazer essa busca desses 10 porcento dentro desses 42 primeiros valores
mediaAmostra= amostra["value_usd"].mean()
print("O valor médio de todos os vinhos é: ", round(mediaPopulacao, 2))
print("O valor médio dos vinhos da amostragem é: ", round(mediaAmostra, 2))

O valor médio de todos os vinhos é:  8398.65
O valor médio dos vinhos da amostragem é:  8487.87

In [73]:
df= pd.read_csv("vinhos.csv")

amostra1= df.sample(frac=0.5)
mediaAmostra1= amostra1["volume_hl"].mean()

amostra2= df.sample(frac=0.5)
mediaAmostra2= amostra2["volume_hl"].mean()

amostra3= df.sample(frac=0.5)
mediaAmostra3= amostra3["volume_hl"].mean()

amostra4= df.sample(frac=0.5)
mediaAmostra4= amostra4["volume_hl"].mean()

amostra5= df.sample(frac=0.5)
mediaAmostra5= amostra5["volume_hl"].mean()

print("-" * 32)
print("MÉDIAS DAS AMOSTRAS")
print("Amostra 1: ", mediaAmostra1)
print("Amostra 2: ", mediaAmostra2)
print("Amostra 3: ", mediaAmostra3)
print("Amostra 4: ", mediaAmostra4)
print("Amostra 5: ", mediaAmostra5)
print("-" * 32)

--------------------------------
MÉDIAS DAS AMOSTRAS
Amostra 1:  2786.338738738739
Amostra 2:  2789.1903153153153
Amostra 3:  2802.1265015015015
Amostra 4:  2789.696021021021
Amostra 5:  2798.103228228228
--------------------------------

In [70]:
df= pd.read_csv("vinhos.csv")

amostra1= df.sample(frac=0.5)
MA1= amostra1["volume_hl"].mean()

amostra2= df.sample(frac=0.5)
MA2= amostra2["volume_hl"].mean()

amostra3= df.sample(frac=0.5)
MA3= amostra3["volume_hl"].mean()

amostra4= df.sample(frac=0.5)
MA4= amostra4["volume_hl"].mean()

amostra5= df.sample(frac=0.5)
MA5= amostra5["volume_hl"].mean()

mediaPopulacao= df["volume_hl"].mean()
mediaAmostraTotal= (MA1 + MA2 + MA3 + MA4 + MA5) / 5

print("-" * 32)
print("COMPARAÇÃO DAS MÉDIAS TOTAIS")
print(f"A média da população é: {mediaPopulacao:.2f}")
print(f"A média das amostras é: {mediaAmostraTotal:.2f}")
print("-" * 32)

--------------------------------
COMPARAÇÃO DAS MÉDIAS TOTAIS
A média da população é: 2798.19
A média das amostras é: 2793.09
--------------------------------

In [67]:
print("-" * 107)
print("Porque o comando random pega valores aleatórios da tabela, vísivel limitando e ausente, da tabela inteira.")
print("-" * 107)

-----------------------------------------------------------------------------------------------------------
Porque o comando random pega valores aleatórios da tabela, vísivel limitando e ausente, da tabela inteira.
-----------------------------------------------------------------------------------------------------------

In [ ]:
import pandas as pd

df= pd.read_csv("vinhos.csv")
df

amp_price= df["value_usd"].max() - df["value_usd"].min() #calculo para pegar a amplitude de preço dos vinhos.
amp_rel= amp_price/df["value_usd"].mean()*100 #calculo para pegar a amplitude relativa do preço dos vinhos.

print(f"Maior valor de vinho: {df["value_usd"].max():.2f}")#comandos para pegar o maior e menor valor.
print(f"Maior valor de vinho: {round(df["value_usd"].min(),2)}")#:.2f e round( ,2) servem para formatar os decimais.

print(f"Amplitude de value_usd: {amp_price:.2f}")
print(f"Amplitude relativa de value_usd: {amp_rel:.2f}")

Maior valor de vinho: 34273.99
Maior valor de vinho: 87.07
Amplitude de value_usd: 34186.92
Amplitude relativa de value_usd: 407.05

In [10]:
import pandas as pd

df= pd.read_csv("vinhos.csv")

var_pop= df["value_usd"].var(ddof=0) #.var e .std serve para pegar variância e desvio padrão.
std_pop= df["value_usd"].std(ddof=0) #ddof=0 serve para pegar todos os dados, e para amostra seria =1, e não da para definir o tamanho da amostragem.
print(f"Variancia value_usd: {var_pop:.2f}")
print(f"Desvio padrão value_usd: {std_pop:.2f}")

Variancia value_usd: 36860976.03
Desvio padrão value_usd: 6071.32

In [ ]:
# Criando uma nova coluna no DataFrame com a amplitude por grupo, o .transform() transforma a coluna no resultado da conta que você coloca no lambda
df['amplitude'] = df.groupby('grape_type')['volume_hl'].transform(lambda x: x.max() - x.min())

# Agora você pode ver o grape_type e a amplitude lado a lado
print(df[['grape_type', 'amplitude']].drop_duplicates())

  grape_type  amplitude
0      Table       6945
1       Wine       6946
2  Sparkling       6945

In [40]:
#jeito mais simples de fazer o cálculo acima
import pandas as pd

df= pd.read_csv("vinhos.csv")

grupo= df.groupby("grape_type")
amp_abs= grupo["volume_hl"].max() - grupo["volume_hl"].min()
amp_rel= amp_abs/grupo["volume_hl"].mean()*100
variancia= grupo["volume_hl"].var(ddof=0)
desvio= grupo["volume_hl"].std(ddof=0)

print("-" * 30)
print(f"Amplitude Absoluta: {amp_abs}")
print("-" * 30)
print(f"Amplitude Relativa: {amp_rel}")
print("-" * 30)
print(f"Variancia: {variancia}")
print("-" * 30)
print(f"Desvio Padrão: {desvio}")
print("-" * 30)

------------------------------
Amplitude Absoluta: grape_type
Sparkling    6945
Table        6945
Wine         6946
Name: volume_hl, dtype: int64
------------------------------
Amplitude Relativa: grape_type
Sparkling    246.846663
Table        250.423053
Wine         247.385735
Name: volume_hl, dtype: float64
------------------------------
Variancia: grape_type
Sparkling    2.795739e+06
Table        2.762211e+06
Wine         2.771513e+06
Name: volume_hl, dtype: float64
------------------------------
Desvio Padrão: grape_type
Sparkling    1672.046276
Table        1661.990198
Wine         1664.786247
Name: volume_hl, dtype: float64
------------------------------

In [26]:
df["relativa"] = df.groupby("grape_type")["volume_hl"].transform(lambda x: x.max() - x.min() / x.mean() * 100)

print(df[['grape_type', 'relativa']].drop_duplicates())

  grape_type     relativa
0      Table  6993.197098
1       Wine  6994.219222
2  Sparkling  6993.222846

In [19]:
import pandas as pd

df= pd.read_csv("vinhos.csv")

dfRel=df.loc[:,["grape_type", "volume_hl"]]
dfRel.groupby("grape_type").var(ddof=0)

               volume_hl
grape_type
Sparkling   2.795739e+06
Table       2.762211e+06
Wine        2.771513e+06

In [18]:
import pandas as pd

df= pd.read_csv("vinhos.csv")

dfVar=df.loc[:,["grape_type", "volume_hl"]]
dfVar.groupby("grape_type").std(ddof=0)

              volume_hl
grape_type
Sparkling   1672.046276
Table       1661.990198
Wine        1664.786247

In [35]:
#primeiro pega a amostra de 25%
amostra= df.sample(frac=0.25, random_state=42)

#agrupa a coluna pela amostra e coloca na variavel grupo_amostra
grupo_amostra= amostra.groupby("grape_type")

#e faz todas as contas com essa variavel que esta ligada com a amostra e o dataframe
amp_abs_amostra= grupo_amostra["volume_hl"].max() - grupo_amostra["volume_hl"].min()
media_amostra= grupo_amostra["volume_hl"].mean()
amp_rel_amostra= (amp_abs_amostra/media_amostra)*100
variancia_amostra= grupo_amostra["volume_hl"].var(ddof=0)
desvio_amostra= grupo_amostra["volume_hl"].std(ddof=0)

#para imprimir monta um novo DataFrame com esse comando do próprio pandas
resultado_amostra= pd.DataFrame({
    "Amplitude Absoluta": amp_abs_amostra,
    "Amplitude Realtiva": amp_rel_amostra,
    "Variancia": variancia_amostra,
    "Desvio Padrão": desvio_amostra
})

print(resultado_amostra.round(2))

            Amplitude Absoluta  Amplitude Realtiva   Variancia  Desvio Padrão
grape_type
Sparkling                 6940              242.19  2773952.54        1665.52
Table                     6945              253.21  2778236.17        1666.80
Wine                      6941              245.91  2808510.86        1675.86

In [36]:
grupo_valor= df.groupby("grape_type")

variancia_valor= grupo_valor["value_usd"].var(ddof=0)
desvio_valor= grupo_valor["value_usd"].std(ddof=0)
grupo_valor_amostra=amostra.groupby("grape_type")
variancia_valor_amostra= grupo_valor_amostra["value_usd"].var(ddof=0)
desvio_valor_amostra= grupo_valor_amostra["value_usd"].std(ddof=0)

resultado_valor= pd.DataFrame({
    "Variância": variancia_valor,
    "Desvio Padrão": desvio_valor,
    "Variancia Amostral": variancia_valor_amostra,
    "Desvio padrão Amostral": desvio_valor_amostra
})

print(resultado_valor.round(2))

              Variância  Desvio Padrão  Variancia Amostral  \
grape_type
Sparkling   36954704.30        6079.04         37458438.78
Table       36198864.88        6016.55         35754571.28
Wine        37424994.65        6117.60         37703821.20

            Desvio padrão Amostral
grape_type
Sparkling                  6120.33
Table                      5979.51
Wine                       6140.34

In [ ]:
import pandas as pd 

df= pd.read_csv("vinhos.csv")

#O IQR serve para dar uma noção da discrepância dos dados, quantio maior o resultado, maior a discrepância.
q1= df["value_usd"].quantile(0.25)
q3= df["value_usd"].quantile(0.75)
iqr= q3-q1

#E os limites servem para dar essa noção mas do teto e do piso dos dados.
limite_inferior= q1 - 1.5 * iqr
limite_superior= q3 + 1.5 * iqr

print("-" * 32)
print("O IQR desta coluna é: ", iqr.round(2))
print("O limite inferior é: ", limite_inferior.round(2))
print("O limite superior é: ", limite_superior.round(2))
print("-" * 32)

--------------------------------
O IQR desta coluna é:  8019.88
O limite inferior é:  -8307.84
O limite superior é:  23771.67
--------------------------------

In [ ]:
import pandas as pd 

df= pd.read_csv("vinhos.csv")

#Esse comando serve para pegar o zcore, ou seja, o quanto o valor que você esta analisamdo esta distante da média.
df["zscore"]= ((df["value_usd"]-df["value_usd"].mean())/df["value_usd"].std(ddof=0)).round(2)
df.head()

,year,month,location,location_type,category,grape_type,volume_hl,value_usd,zscore
0,2015,1,AC,Brazil_State,Production,Table,910,1782.31,-1.09
1,2015,1,AC,Brazil_State,Production,Wine,3822,11435.90,0.50
2,2015,1,AC,Brazil_State,Production,Sparkling,516,902.97,-1.23
3,2015,1,AC,Brazil_State,Sales,Table,3494,10491.74,0.34
4,2015,1,AC,Brazil_State,Sales,Wine,180,279.26,-1.34

In [ ]:
import pandas as pd 

df= pd.read_csv("vinhos.csv")

grupo= df.groupby("grape_type")

q1= grupo["value_usd"].quantile(0.25)
q3= grupo["value_usd"].quantile(0.75)
iqr= q3-q1

limite_inferior= q1 - 1.5 * iqr
limite_superior= q3 + 1.5 * iqr

#O | é o operador lógico OU, para mostrar os dois valores das duas linhas deste DataFrame 

outliers_iqr= df[
    (df["volume_hl"]<df["grape_type"].map(limite_inferior))|
    (df["volume_hl"]>df["grape_type"].map(limite_superior))
]
print("-" * 30)
print(limite_inferior)
print("-" * 30)
print(limite_superior)
print("-" * 30)
print(outliers_iqr)
print("-" * 30)

------------------------------
grape_type
Sparkling   -8214.87250
Table       -8335.65625
Wine        -8384.50750
Name: value_usd, dtype: float64
------------------------------
grape_type
Sparkling    23747.00750
Table        23705.15375
Wine         23871.83250
Name: value_usd, dtype: float64
------------------------------
Empty DataFrame
Columns: [year, month, location, location_type, category, grape_type, volume_hl, value_usd]
Index: []
------------------------------

In [ ]:
import pandas as pd 

df= pd.read_csv("vinhos.csv")

media= df.groupby("grape_type")["volume_hl"].transform("mean")
std= df.groupby("grape_type")["volume_hl"].transform(lambda x: x.std(ddof=0))
df["zscore"]= (df["volume_hl"]-media)/std

#A lógica do >/<3 serve para mostrar os números que estçao muito acima da média ou muit abaixo da média
#O | é o operador lógico OU, para mostrar os dois valores das duas linhas deste DataFrame 
outliers_zscore= df[
    (df["zscore"]>3)|
    (df["zscore"]<3)
]
amostra= df.sample(frac=0.25, random_state=42)

print("-" * 30)
print(media)
print("-" * 30)
print(std)
print("-" * 30)
print(outliers_zscore)
print("-" * 30)
print(amostra)
print("-" * 30)

------------------------------
0        2773.306982
1        2807.760923
2        2813.487500
3        2773.306982
4        2807.760923
            ...
26635    2807.760923
26636    2813.487500
26637    2773.306982
26638    2807.760923
26639    2813.487500
Name: volume_hl, Length: 26640, dtype: float64
------------------------------
0        1661.990198
1        1664.786247
2        1672.046276
3        1661.990198
4        1664.786247
            ...
26635    1664.786247
26636    1672.046276
26637    1661.990198
26638    1664.786247
26639    1672.046276
Name: volume_hl, Length: 26640, dtype: float64
------------------------------
       year  month location location_type    category grape_type  volume_hl  \
0      2015      1       AC  Brazil_State  Production      Table        910
1      2015      1       AC  Brazil_State  Production       Wine       3822
2      2015      1       AC  Brazil_State  Production  Sparkling        516
3      2015      1       AC  Brazil_State       Sales      Table       3494
4      2015      1       AC  Brazil_State       Sales       Wine        180
...     ...    ...      ...           ...         ...        ...        ...
26635  2024     12    China       Country      Import       Wine       3574
26636  2024     12    China       Country      Import  Sparkling        825
26637  2024     12    China       Country      Export      Table       2115
26638  2024     12    China       Country      Export       Wine       2107
26639  2024     12    China       Country      Export  Sparkling       6813

       value_usd    zscore
0        1782.31 -1.121130
1       11435.90  0.609231
2         902.97 -1.374057
3       10491.74  0.433633
4         279.26 -1.578437
...          ...       ...
26635   12650.27  0.460263
26636    3844.02 -1.189254
26637    6153.84 -0.396096
26638    9355.02 -0.420931
26639   23101.92  2.391987

[26640 rows x 9 columns]
------------------------------
       year  month      location location_type    category grape_type  \
11959  2021      2            PE  Brazil_State  Production       Wine
8121   2017     10            MS  Brazil_State       Sales      Table
1610   2017      5            AP  Brazil_State  Production  Sparkling
12624  2020      5            PI  Brazil_State  Production      Table
20086  2023     12         Italy       Country      Export       Wine
...     ...    ...           ...           ...         ...        ...
17177  2023      7            SC  Brazil_State       Sales  Sparkling
115    2016      8            AC  Brazil_State  Production       Wine
21374  2021     11         Spain       Country      Import  Sparkling
14046  2020      2            RN  Brazil_State  Production      Table
24566  2016      3  South Africa       Country      Import  Sparkling

       volume_hl  value_usd    zscore
11959       4567   10371.45  1.056736
8121        4857   12684.12  1.253734
1610        1802    3478.26 -0.604940
12624       2571    8283.05 -0.121726
20086       4146   14199.45  0.803850
...          ...        ...       ...
17177       4230   10395.59  0.847173
115         4037    9754.09  0.738377
21374       1922    9275.65 -0.533172
14046       1597    5362.36 -0.707770
24566       2188    9564.51 -0.374085

[6660 rows x 9 columns]
------------------------------

In [41]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.barplot(
    data= df,
    x= "category",
    y= "value_usd",
    estimator= "mean"
)
plt.title("preço medio por categoria")
plt.xlabel("categoria")
plt.ylabel("preço medio")
plt.show()

ModuleNotFoundError: No module named 'seaborn'